### ISSUE TITLE
Implement css nesting

### ISSUE THREAD

**Issue by Hadil66** [Hadil66/Meesterproef#16]

**Comment by Hadil66** [comment]
CSS Nesting wasn't working properly so I've installed SASS and used `scss`.

```scss
.big-menu {
    background-color: rgba($gray-25, 0.75); 
    display: flex;
    flex-direction: row;
    gap: $spacing-small - 1px; 
    height: 3em;
    padding: 0 $spacing-medium;
    border-radius: 50px; 
    list-style: none;
    margin: 0;
    align-items: center;
  
    .big-menu-item {
      padding: 0;
  
      a {
        font-size: $font-size-base; 
        text-decoration: none;
        color: $text-color-base;
        padding: $spacing-extra-small ($spacing-small * 0.75); 
        display: block;
        border-radius: $border-radius-default / 2; 
  
        &:hover,
        &:focus-within {
          background-color: rgba($gray-900, 0.05); 
        }
      }
    }
  }
  ```
