### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Hadil66** [Hadil66/Meesterproef#18]
- Add a global styling sheet
- Add a font `Host Grotesk`
- Add variables

**Comment by Hadil66** [comment]
- The underscore in the variables file name signifies that this is a "partial" file, meant to be imported and not compiled on its own.

I've added this to everything to ensure that it meets the requirements of the [WCAG 1.4.12 ](https://digitaaltoegankelijk.nl/wcag-uitgelegd/1-4-12-tekstafstand-wcag-niveau-aa/)

```scss
* {
line-height: 1.5 !important;
letter-spacing: 0.12em !important;
word-spacing: 0.16em !important; }
p {
margin-bottom: 2em !important;
}
```
